Add chocolatey and scoop installation in docs
workspacer/workspacer pull request #208
Opened 2021-05-31 10:45 UTC by sitiom

workspacer is available in Scoop, and recently I have started to maintain a [Chocolatey package of workspacer](https://community.chocolatey.org/packages/workspacer). It might be good to add these installation methods to the docs.

2021-05-31 12:35 UTC, josteink commented
That's absolutely awesome and I definitely welcome this initiative￼!

That said, I think having the official release channel listed first and having third party distribution methods listed makes more sense. 

￼￼￼If you can order things that way, I will certainly approve of this PR. ￼

What do you say @rickbutton ? 🙂

2021-05-31 13:05 UTC, sitiom commented
> That said, I think having the official release channel listed first and having third party distribution methods listed after that makes more sense.
> 
> ￼￼￼If you can order things that way, I will certainly approve of this PR. ￼

Sure, I will fix that.

2021-05-31 13:21 UTC, josteink approved these changes

2021-06-23 18:09 UTC, josteink commented
PRs haven’t been merged in *months* and Rick haven’t been answering emails either. 

Right now it seems a fork is needed to keep workspacer going forwards. 

I’m discussing this in a issue here: https://github.com/rickbutton/workspacer/issues/211

Feel free to let me know your thoughts.

2021-06-27 08:46 UTC, dalyIsaac requested changes
The URL needs to be updated, but otherwise LGTM!

2021-06-27 08:46 UTC, dalyIsaac commented on docs/content/quickstart.md
> +download the installer or the zip file from the [Releases](https://github.com/rickbutton/workspacer/releases/latest) page and install/unzip it anywhere you like.
```suggestion
download the installer or the zip file from the [Releases](https://github.com/workspacer/workspacer/releases/latest) page and install/unzip it anywhere you like. 
```

2021-06-27 17:40 UTC, josteink commented
@dalyIsaac: Your suggestion looks fixed now. Can you click “Review” and formally “approve” the PR? 🙂

2021-06-27 20:31 UTC, dalyIsaac approved these changes

2021-06-27 20:42 UTC, merged

2021-06-27 20:43 UTC, josteink commented
Resolved the conflict and finally got this merged. Thanks for helping out everyone. 

We’re in a package-manager now 😎