Doc: Fix layout engine names, add TextWidget, add details to keybinding configuration
workspacer/workspacer pull request #225
Opened 2021-06-29 18:59 UTC by egoexpress

This PR adds some documentation to make it easier to configure Workspacer following the docs/website:

- It fixes the used names of the layout engines to match the class names
- It adds the TextWidget which is present, but not yet mentioned in the docs
- It adds pointers to the key modifier names and the key names so setting up keybindings becomes more clear

2021-06-29 20:57 UTC, dalyIsaac requested changes
Other than the one requested change, LGTM!

2021-06-29 20:57 UTC, dalyIsaac commented on docs/content/config.md
> +Add a keybindung using `Keybinds.Subscribe`. See [Keys.cs](https://github.com/workspacer/workspacer/blob/master/src/workspacer.Shared/Keybind/Keys.cs) for all the available key names.
```suggestion
Add a keybinding using `Keybinds.Subscribe`. See [Keys.cs](https://github.com/workspacer/workspacer/blob/master/src/workspacer.Shared/Keybind/Keys.cs) for all the available key names.
```

2021-06-29 23:20 UTC, dalyIsaac approved these changes
LGTM!

2021-06-30 00:57 UTC, N1x0 approved these changes
lgtm

2021-06-30 00:57 UTC, merged