BarPlugin PerformanceWidget
workspacer/workspacer pull request #272
Opened 2021-11-03 07:30 UTC by denjukebox

This PR implements 3 performance counter based widgets to display statistics about the system in the bar.

- Extendable PerformanceCounter base class
- CPU Widget
- Memory Widget
- Network Widget

The original idea was suggested by @adolfocorreia
https://github.com/workspacer/workspacer/issues/265

2021-11-03 11:27 UTC, dalyIsaac requested changes
This looks awesome!

Can you also provide some documentation in `/docs` for potential usage?

2021-11-03 11:27 UTC, dalyIsaac commented on src/workspacer.Bar/Widgets/PerformanceWidget.cs
> +            var amount = value;
I don't think the `amount` variable is necessary.

2021-11-03 11:27 UTC, dalyIsaac commented on src/workspacer.Bar/Widgets/PerformanceWidget.cs
> +                icon = char.ConvertFromUtf32(int.Parse(Icon, System.Globalization.NumberStyles.HexNumber));
I think it'd be nice if we could allow custom text and emojis.

2021-11-03 11:27 UTC, dalyIsaac commented on src/workspacer.Bar/Widgets/PerformanceWidget.cs
> +        protected override Action ClickAction => () => Process.Start("explorer.exe", @"shell:::{26EE0668-A00A-44D7-9371-BEB064C98683}\3");
Can you add a comment describing what this points to?

2021-11-04 15:12 UTC, adolfocorreia commented
Great work on this new PerformanceWidget, @denjukebox!

I was not able to run/test your code, but if I may make a comment on this PR, I would suggest against calling `_counter.NextValue()` in the `GetParts()` function and poll the counter only in the timer callback instead. That was an issue I had in my implementation. The problem was that the CPU/memory widget might be redrawn because of other events (e.g. a TimeWidget update), and a new counter poll might be run before the next timer event. You could try to reproduce this behavior by setting the PerformanceWidget with a long update interval (e.g. 1 minute) and a TimeWidget with a short update interval (e.g. 1 second).

2021-11-05 09:38 UTC, dalyIsaac commented
Thanks for adding the documentation. I think it'd be good to update based on @adolfocorreia's feedback.

2021-11-05 16:49 UTC, denjukebox commented
@adolfocorreia Thanks for noticing the update issue! I'd seen the numbers updating a bit quickly put didn't put things together.

2021-11-05 18:56 UTC, adolfocorreia commented
Glad I could help!

But I think it is still necessary to call `Context.MarkDirty()` in the timer callback, isn't it? Otherwise the PerformanceWidget might not be updated on the screen if there aren't other redraw events.

2021-11-08 07:59 UTC, dalyIsaac commented
> Glad I could help!
> 
> But I think it is still necessary to call `Context.MarkDirty()` in the timer callback, isn't it? Otherwise the PerformanceWidget might not be updated on the screen if there aren't other redraw events.

@denjukebox I think this might be the case.

2021-11-08 20:27 UTC, denjukebox commented
Yup totally missed that. I added it in again with an overridable update function for the timer.

2021-11-09 04:24 UTC, dalyIsaac commented
For `NetworkPerformanceWidget`, I think it'd be worth adding that to select the appropriate instance, you can get the name from Device Manager:

![image](https://user-images.githubusercontent.com/17995621/140861324-5a63bff2-559f-4279-9652-9a7568dae7d1.png)

would be instantiated as:

```csharp
new NetworkPerformanceWidget("Intel[R] Ethernet Connection [7] I219-V"),
```

2022-07-14 20:01 UTC, xd999e commented
Any plans to merge this feature into main?

2022-07-24 05:55 UTC, denjukebox commented
Apparently this was still blocked by @dalyIsaac his request for documentation. I've done this in the mean while but I guess this has to be checked off still? Been away from this project for a bit now.

2022-07-24 06:04 UTC, dalyIsaac approved these changes

2022-07-24 06:17 UTC, merged

2022-07-29 00:19 UTC, denjukebox commented
@dalyIsaac  Thanks for the merge an grammar fixes!

2022-10-15 21:45 UTC, pranavpa8788 commented
Whenever I use any of the performance widgets I get the The type or namespace name 'NetworkPerformanceWidget' could not be found (are you missing a using directive or an assembly reference?). 

I am using the latest verison of workspacer. Do I have to manually compile the dll file?